import React, { useState, useEffect } from 'react';
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { 
  Search, 
  BrainCircuit, 
  Database, 
  LineChart, 
  FileText, 
  Download, 
  ChevronRight, 
  CheckCircle2, 
  Loader2,
  Share2
} from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { LineChart as ReLineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, AreaChart, Area, ScatterChart, Scatter, ZAxis } from 'recharts';

const AgentStep = ({ title, icon: Icon, status, delay }) => (
  <motion.div 
    initial={{ opacity: 0, y: 10 }}
    animate={{ opacity: 1, y: 0 }}
    transition={{ delay }}
    className={`flex items-center gap-3 p-3 rounded-lg border ${
      status === 'active' ? 'bg-blue-900/20 border-blue-500/50 text-blue-400' :
      status === 'completed' ? 'bg-emerald-900/20 border-emerald-500/50 text-emerald-400' :
      'bg-gray-900/50 border-gray-800 text-gray-500'
    }`}
  >
    {status === 'active' ? (
      <Loader2 className="w-5 h-5 animate-spin" />
    ) : status === 'completed' ? (
      <CheckCircle2 className="w-5 h-5" />
    ) : (
      <div className="w-5 h-5 rounded-full border-2 border-gray-700" />
    )}
    <div className="flex-1">
      <div className="flex items-center gap-2">
        <Icon className="w-4 h-4" />
        <span className="font-medium text-sm">{title}</span>
      </div>
    </div>
  </motion.div>
);

export default function Research() {
  const [query, setQuery] = useState("");
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [stage, setStage] = useState(0); // 0: idle, 1: factors, 2: history, 3: scenarios, 4: complete
  const [showResult, setShowResult] = useState(false);

  // Mock data for the result
  // Mock data for the results
  const scenarioData = [
    { name: 'Scenario A: Bull Case', prob: 20, description: "Highly favorable regulatory outcome" },
    { name: 'Scenario B: Base Case', prob: 45, description: "Status quo maintained, moderate growth" },
    { name: 'Scenario C: Bear Case', prob: 25, description: "Regulatory headwinds increase" },
    { name: 'Scenario D: Black Swan', prob: 10, description: "Unexpected systemic shock" },
  ];

  const factorData = [
    { x: 85, y: 70, z: 100, name: 'Inflation Data', impact: 'High', direction: 'Negative' },
    { x: 45, y: 90, z: 80, name: 'ETF Inflows', impact: 'Medium', direction: 'Positive' },
    { x: 65, y: 50, z: 60, name: 'Mining Difficulty', impact: 'Medium', direction: 'Positive' },
    { x: 30, y: 40, z: 40, name: 'Retail Sentiment', impact: 'Low', direction: 'Neutral' },
    { x: 90, y: 85, z: 95, name: 'Fed Policy', impact: 'High', direction: 'Negative' },
  ];

  const historicalData = [
    { event: "2017 Bull Run", similarity: 88, outcome: "Hit" },
    { event: "2021 Peak", similarity: 92, outcome: "Hit" },
    { event: "2019 Echo Bubble", similarity: 65, outcome: "Miss" },
  ];

  const handleSearch = (e) => {
    e.preventDefault();
    if (!query) return;
    
    setIsAnalyzing(true);
    setStage(1);
    setShowResult(false);

    // Simulate agent steps
    setTimeout(() => setStage(2), 2000);
    setTimeout(() => setStage(3), 4500);
    setTimeout(() => {
      setStage(4);
      setShowResult(true);
      setIsAnalyzing(false);
    }, 7000);
  };

  return (
    <div className="max-w-7xl mx-auto space-y-8 min-h-[calc(100vh-100px)] flex flex-col">
      {/* Header Section */}
      <div className="text-center space-y-4 py-8">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-900/20 text-blue-400 border border-blue-800 text-xs font-mono mb-4">
          <BrainCircuit className="w-3 h-3" />
          AUTONOMOUS RESEARCH ANALYST V2.0
        </div>
        <h1 className="text-4xl md:text-5xl font-bold text-white tracking-tight">
          Deep Market Intelligence
        </h1>
        <p className="text-gray-400 max-w-2xl mx-auto text-lg">
          Institutional-grade research generated by autonomous agent swarms.
          Reference class forecasting, not intuition.
        </p>
      </div>

      {/* Search Bar */}
      <div className="max-w-3xl mx-auto w-full relative z-10">
        <form onSubmit={handleSearch} className="relative group">
          <div className="absolute inset-0 bg-gradient-to-r from-blue-500 to-purple-500 rounded-xl blur opacity-20 group-hover:opacity-30 transition-opacity" />
          <div className="relative bg-[#0a0a0c] border border-gray-700 rounded-xl flex items-center p-2 shadow-2xl">
            <Search className="w-6 h-6 text-gray-500 ml-4" />
            <input 
              type="text" 
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder="Enter a prediction question (e.g., 'Will Bitcoin hit $100k by Q4?')" 
              className="flex-1 bg-transparent border-none text-white px-4 py-3 focus:outline-none text-lg placeholder:text-gray-600"
            />
            <Button 
              type="submit" 
              disabled={isAnalyzing || !query}
              className="bg-blue-600 hover:bg-blue-700 text-white px-8 py-6 rounded-lg font-medium transition-all disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {isAnalyzing ? <Loader2 className="animate-spin" /> : 'Run Analysis'}
            </Button>
          </div>
        </form>
      </div>

      <div className="flex-1 grid grid-cols-1 lg:grid-cols-12 gap-8 mt-8">
        {/* Agent Status Panel */}
        <div className="lg:col-span-4 space-y-4">
          <Card className="bg-[#111214] border-gray-800 h-full">
            <CardContent className="p-6">
              <h3 className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-6">Agent Operation Swarm</h3>
              
              <div className="space-y-3">
                <AgentStep 
                  title="Factor Decomposition" 
                  icon={BrainCircuit} 
                  status={stage === 1 ? 'active' : stage > 1 ? 'completed' : 'idle'} 
                  delay={0}
                />
                <AgentStep 
                  title="Historical Base Rates" 
                  icon={Database} 
                  status={stage === 2 ? 'active' : stage > 2 ? 'completed' : 'idle'} 
                  delay={0.1}
                />
                <AgentStep 
                  title="Scenario Modeling" 
                  icon={LineChart} 
                  status={stage === 3 ? 'active' : stage > 3 ? 'completed' : 'idle'} 
                  delay={0.2}
                />
                <AgentStep 
                  title="Report Synthesis" 
                  icon={FileText} 
                  status={stage === 4 ? 'completed' : 'idle'} 
                  delay={0.3}
                />
              </div>

              {stage > 0 && (
                <div className="mt-8 p-4 bg-[#0a0a0c] rounded-lg border border-gray-800 font-mono text-xs text-green-400 h-48 overflow-y-auto">
                  <div className="space-y-2">
                    <p className="opacity-50">[SYSTEM] Initializing swarm...</p>
                    {stage >= 1 && <p>[FACTOR_AGENT] Identifying key variables for "{query}"...</p>}
                    {stage >= 1 && <p className="ml-2 text-gray-500">&gt; Detected: Market Sentiment, Reg. Environment, Macro Trends</p>}
                    {stage >= 2 && <p>[HISTORICAL_AGENT] Querying vector DB for precedents (1990-2023)...</p>}
                    {stage >= 2 && <p className="ml-2 text-gray-500">&gt; Found 12 similar events with r^2 {'>'} 0.85</p>}
                    {stage >= 3 && <p>[SCENARIO_AGENT] Running Monte Carlo simulations (n=10000)...</p>}
                    {stage >= 4 && <p className="text-emerald-500">[ORCHESTRATOR] Analysis complete. Generating artifacts.</p>}
                  </div>
                </div>
              )}
            </CardContent>
          </Card>
        </div>

        {/* Results View */}
        <div className="lg:col-span-8">
          <AnimatePresence mode="wait">
            {showResult ? (
              <motion.div 
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                className="space-y-6"
              >
                <div className="bg-[#111214] border border-gray-800 rounded-xl overflow-hidden">
                  <div className="p-6 border-b border-gray-800 flex justify-between items-start">
                    <div>
                      <h2 className="text-2xl font-bold text-white">{query}</h2>
                      <div className="flex gap-2 mt-2">
                        <Badge className="bg-emerald-900/30 text-emerald-400 border-emerald-800">Confidence: High</Badge>
                        <Badge className="bg-blue-900/30 text-blue-400 border-blue-800">Sources: 14</Badge>
                      </div>
                    </div>
                    <Button variant="outline" className="border-gray-700 text-gray-300 hover:text-white hover:bg-gray-800">
                      <Download className="w-4 h-4 mr-2" />
                      Export PDF
                    </Button>
                  </div>
                  
                  <div className="p-6 grid grid-cols-1 md:grid-cols-2 gap-8">
                    <div>
                      <h3 className="text-sm font-bold text-gray-400 uppercase mb-4">Probability Distribution</h3>
                      <div className="h-64 w-full">
                        <ResponsiveContainer width="100%" height="100%">
                          <AreaChart data={scenarioData}>
                            <defs>
                              <linearGradient id="colorProb" x1="0" y1="0" x2="0" y2="1">
                                <stop offset="5%" stopColor="#3b82f6" stopOpacity={0.3}/>
                                <stop offset="95%" stopColor="#3b82f6" stopOpacity={0}/>
                              </linearGradient>
                            </defs>
                            <CartesianGrid strokeDasharray="3 3" stroke="#1f2937" />
                            <XAxis dataKey="name" stroke="#4b5563" fontSize={10} tickFormatter={(val) => val.split(':')[0]} />
                            <YAxis stroke="#4b5563" fontSize={12} />
                            <Tooltip 
                              contentStyle={{ backgroundColor: '#111214', borderColor: '#374151' }}
                              itemStyle={{ color: '#fff' }}
                            />
                            <Area type="monotone" dataKey="prob" stroke="#3b82f6" fillOpacity={1} fill="url(#colorProb)" />
                          </AreaChart>
                        </ResponsiveContainer>
                      </div>
                    </div>

                    <div className="space-y-4">
                      <h3 className="text-sm font-bold text-gray-400 uppercase mb-2">Executive Summary</h3>
                      <p className="text-gray-300 text-sm leading-relaxed">
                        Based on historical precedents of similar asset classes, the base rate for this event is 32%. 
                        However, current market factors (Fed Policy, Inflation) provide a strong positive adjustment (+15%).
                      </p>
                      
                      <div className="space-y-2 mt-4">
                        <div className="flex justify-between text-sm">
                          <span className="text-gray-500">Base Rate (Historical)</span>
                          <span className="text-gray-300">32%</span>
                        </div>
                        <div className="flex justify-between text-sm">
                          <span className="text-gray-500">Adjustment Factor</span>
                          <span className="text-emerald-400">+15%</span>
                        </div>
                        <div className="h-px bg-gray-800 my-2" />
                        <div className="flex justify-between text-lg font-bold">
                          <span className="text-white">Final Probability</span>
                          <span className="text-blue-400">47%</span>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div className="p-6 border-t border-gray-800 grid grid-cols-1 md:grid-cols-2 gap-8">
                     {/* Factor Analysis Scatter */}
                     <div>
                        <h3 className="text-sm font-bold text-gray-400 uppercase mb-4">Factor Impact Analysis</h3>
                        <div className="h-64 w-full bg-[#0f1012] rounded-lg border border-gray-800 p-2">
                           <ResponsiveContainer width="100%" height="100%">
                              <ScatterChart margin={{ top: 20, right: 20, bottom: 20, left: 20 }}>
                                 <CartesianGrid strokeDasharray="3 3" stroke="#1f2937" />
                                 <XAxis type="number" dataKey="x" name="Impact" unit="%" stroke="#4b5563" label={{ value: 'Impact Score', position: 'bottom', fill: '#4b5563', fontSize: 10 }} />
                                 <YAxis type="number" dataKey="y" name="Confidence" unit="%" stroke="#4b5563" label={{ value: 'Confidence', angle: -90, position: 'left', fill: '#4b5563', fontSize: 10 }} />
                                 <ZAxis type="number" dataKey="z" range={[50, 400]} name="Weight" />
                                 <Tooltip 
                                    cursor={{ strokeDasharray: '3 3' }} 
                                    content={({ active, payload }) => {
                                       if (active && payload && payload.length) {
                                       const data = payload[0].payload;
                                       return (
                                          <div className="bg-[#111214] border border-gray-700 p-2 rounded shadow-lg">
                                             <p className="font-bold text-white">{data.name}</p>
                                             <p className="text-xs text-gray-400">Impact: {data.x}%</p>
                                             <p className="text-xs text-gray-400">Confidence: {data.y}%</p>
                                             <p className={`text-xs ${data.direction === 'Positive' ? 'text-emerald-400' : 'text-red-400'}`}>
                                                {data.direction}
                                             </p>
                                          </div>
                                       );
                                       }
                                       return null;
                                    }}
                                 />
                                 <Scatter name="Factors" data={factorData} fill="#3b82f6" shape="circle" />
                              </ScatterChart>
                           </ResponsiveContainer>
                        </div>
                     </div>

                     {/* Historical Precedents */}
                     <div>
                        <h3 className="text-sm font-bold text-gray-400 uppercase mb-4">Historical Precedents</h3>
                        <div className="bg-[#0f1012] rounded-lg border border-gray-800 overflow-hidden">
                           <table className="w-full text-sm">
                              <thead className="bg-[#1a1b1e] text-gray-500">
                                 <tr>
                                    <th className="p-3 text-left font-medium">Event</th>
                                    <th className="p-3 text-center font-medium">Similarity</th>
                                    <th className="p-3 text-right font-medium">Outcome</th>
                                 </tr>
                              </thead>
                              <tbody className="divide-y divide-gray-800">
                                 {historicalData.map((event, i) => (
                                    <tr key={i} className="hover:bg-gray-800/30">
                                       <td className="p-3 text-gray-300">{event.event}</td>
                                       <td className="p-3 text-center">
                                          <Badge variant="outline" className={`border-none ${event.similarity > 80 ? 'text-emerald-400 bg-emerald-900/10' : 'text-yellow-400 bg-yellow-900/10'}`}>
                                             {event.similarity}%
                                          </Badge>
                                       </td>
                                       <td className="p-3 text-right text-gray-400">{event.outcome}</td>
                                    </tr>
                                 ))}
                              </tbody>
                           </table>
                        </div>
                     </div>
                  </div>
                  
                  <div className="bg-[#0a0a0c] p-4 border-t border-gray-800 flex justify-between items-center">
                    <span className="text-xs text-gray-500">Analysis ID: 8f7e-29a1-4b3c</span>
                    <div className="flex gap-2">
                       <Button variant="ghost" size="sm" className="text-gray-400 hover:text-white">
                         <Share2 className="w-4 h-4 mr-2" /> Share Report
                       </Button>
                    </div>
                  </div>
                </div>
              </motion.div>
            ) : (
              <div className="h-full flex flex-col items-center justify-center text-gray-600 space-y-4 min-h-[400px] border-2 border-dashed border-gray-800 rounded-xl">
                <BrainCircuit className="w-16 h-16 opacity-20" />
                <p>Waiting for research query...</p>
              </div>
            )}
          </AnimatePresence>
        </div>
      </div>
    </div>
  );
}